<?php

use Illuminate\Database\Seeder;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::table('groups')->truncate();
        $member = [
            [
                'name' => 'Steve Yoo',
                'kor_name' => '유용훈',
                'gender' => 'Male',
                'email' => 'steve.yoo@intrustenergysolution.com',
                'email_verified_at' => now(),
                'password' => bcrypt('111111'),
                'remember_token' => Str::random(10),
                'position' => 'IT Manager',
                'kor_position' => '과장',
                'is_active' => true,
                'mobile' => '+82 (0)10 0000 0000',
                'phone' => '+82 (0)52 252 9835',
                'uuid' => '',
                'avatar' => '',
                'timezone' => 'Europe/Rome',
                'member_group_id' => '1',
                'branch_id' => '1',
                'department_id' => '1',
                'position_id' => '1',
            ],

            [
                'name' => 'Nguyen Vu Quang  Huy',
                'kor_name' => '휘',
                'gender' => 'Male',
                'email' => 'huy.nguyen@intrustenergysolution.com',
                'email_verified_at' => now(),
                'password' => bcrypt('111111'),
                'remember_token' => Str::random(10),
                'position' => 'Business Coordinator',
                'kor_position' => 'Business Coordinator',
                'is_active' => true,
                'mobile' => '+82 (0)10 0000 0000',
                'phone' => '+82 (0)52 252 9835',
                'uuid' => '',
                'avatar' => '',
                'timezone' => 'Europe/Rome',
                'member_group_id' => '1',
                'branch_id' => '1',
                'department_id' => '1',
                'position_id' => '1',
            ],

            [
                'name' => 'Serian Yu',
                'kor_name' => '유하윤',
                'gender' => 'Female',
                'email' => 'serina.yu@intrustenergysolution.com',
                'email_verified_at' => now(),
                'password' => bcrypt('111111'),
                'remember_token' => Str::random(10),
                'position' => 'Your Position',
                'kor_position' => 'Your Position',
                'is_active' => true,
                'mobile' => '+82 (0)10 0000 0000',
                'phone' => '+82 (0)52 252 9835',
                'uuid' => '',
                'avatar' => '',
                'timezone' => 'Europe/Rome',
                'member_group_id' => '1',
                'branch_id' => '1',
                'department_id' => '1',
                'position_id' => '1',
            ],

            [
                'name' => 'Scott Kim',
                'kor_name' => '김성휘',
                'gender' => 'Male',
                'email' => 'scott.kim@intrustenergysolution.com',
                'email_verified_at' => now(),
                'password' => bcrypt('111111'),
                'remember_token' => Str::random(10),
                'position' => 'Your Position',
                'kor_position' => 'Your Position',
                'is_active' => true,
                'mobile' => '+82 (0)10 0000 0000',
                'phone' => '+82 (0)52 252 9835',
                'uuid' => '',
                'avatar' => '',
                'timezone' => 'Europe/Rome',
                'member_group_id' => '1',
                'branch_id' => '1',
                'department_id' => '1',
                'position_id' => '1',
            ],

            [
                'name' => 'John',
                'kor_name' => '염정헌',
                'gender' => 'Male',
                'email' => 'john@intrustenergysolution.com',
                'email_verified_at' => now(),
                'password' => bcrypt('111111'),
                'remember_token' => Str::random(10),
                'position' => 'Your Position',
                'kor_position' => 'Your Position',
                'is_active' => true,
                'mobile' => '+82 (0)10 0000 0000',
                'phone' => '+82 (0)52 252 9835',
                'uuid' => '',
                'avatar' => '',
                'timezone' => 'Europe/Rome',
                'member_group_id' => '1',
                'branch_id' => '1',
                'department_id' => '1',
                'position_id' => '1',
            ],

            [
                'name' => 'YT Kim',
                'kor_name' => '김용태',
                'gender' => 'Male',
                'email' => 'yt.kim@intrustenergysolution.com',
                'email_verified_at' => now(),
                'password' => bcrypt('111111'),
                'remember_token' => Str::random(10),
                'position' => 'Your Position',
                'kor_position' => 'Your Position',
                'is_active' => true,
                'mobile' => '+82 (0)10 0000 0000',
                'phone' => '+82 (0)52 252 9835',
                'uuid' => '',
                'avatar' => '',
                'timezone' => 'Europe/Rome',
                'member_group_id' => '1',
                'branch_id' => '1',
                'department_id' => '1',
                'position_id' => '1',
            ],

            [
                'name' => 'Lisa Kim',
                'kor_name' => '김이슬',
                'gender' => 'female',
                'email' => 'lisa.kim@intrustenergysolution.com',
                'email_verified_at' => now(),
                'password' => bcrypt('111111'),
                'remember_token' => Str::random(10),
                'position' => 'Your Position',
                'kor_position' => 'Your Position',
                'is_active' => true,
                'mobile' => '+82 (0)10 0000 0000',
                'phone' => '+82 (0)52 252 9835',
                'uuid' => '',
                'avatar' => '',
                'timezone' => 'Europe/Rome',
                'member_group_id' => '1',
                'branch_id' => '1',
                'department_id' => '1',
                'position_id' => '1',
            ],

            [
                'name' => 'KC Kim',
                'kor_name' => '김기찬',
                'gender' => 'Male',
                'email' => 'kc.kim@intrustenergysolution.com',
                'email_verified_at' => now(),
                'password' => bcrypt('111111'),
                'remember_token' => Str::random(10),
                'position' => 'Your Position',
                'kor_position' => 'Your Position',
                'is_active' => true,
                'mobile' => '+82 (0)10 0000 0000',
                'phone' => '+82 (0)52 252 9835',
                'uuid' => '',
                'avatar' => '',
                'timezone' => 'Europe/Rome',
                'member_group_id' => '1',
                'branch_id' => '1',
                'department_id' => '1',
                'position_id' => '1',
            ],

            [
                'name' => 'Hyun-su Lim',
                'kor_name' => '임현수',
                'gender' => 'Male',
                'email' => 'hs.lim@intrustenergysolution.com',
                'email_verified_at' => now(),
                'password' => bcrypt('111111'),
                'remember_token' => Str::random(10),
                'position' => 'Your Position',
                'kor_position' => 'Your Position',
                'is_active' => true,
                'mobile' => '+82 (0)10 0000 0000',
                'phone' => '+82 (0)52 252 9835',
                'uuid' => '',
                'avatar' => '',
                'timezone' => 'Europe/Rome',
                'member_group_id' => '1',
                'branch_id' => '1',
                'department_id' => '1',
                'position_id' => '1',
            ],

            [
                'name' => 'Iron Kim',
                'kor_name' => '김재철',
                'gender' => 'Male',
                'email' => 'iron.kim@intrustenergysolution.com',
                'email_verified_at' => now(),
                'password' => bcrypt('111111'),
                'remember_token' => Str::random(10),
                'position' => 'Your Position',
                'kor_position' => 'Your Position',
                'is_active' => true,
                'mobile' => '+82 (0)10 0000 0000',
                'phone' => '+82 (0)52 252 9835',
                'uuid' => '',
                'avatar' => '',
                'timezone' => 'Europe/Rome',
                'member_group_id' => '1',
                'branch_id' => '1',
                'department_id' => '1',
                'position_id' => '1',
            ],

            [
                'name' => 'Nikita Han',
                'kor_name' => '니키타',
                'gender' => 'Female',
                'email' => 'nikita@intrustenergysolution.com',
                'email_verified_at' => now(),
                'password' => bcrypt('111111'),
                'remember_token' => Str::random(10),
                'position' => 'Your Position',
                'kor_position' => 'Your Position',
                'is_active' => true,
                'mobile' => '+82 (0)10 0000 0000',
                'phone' => '+82 (0)52 252 9835',
                'uuid' => '',
                'avatar' => '',
                'timezone' => 'Europe/Rome',
                'member_group_id' => '1',
                'branch_id' => '1',
                'department_id' => '1',
                'position_id' => '1',
            ]
        ];
        DB::table('users')->insert($member);
    }
}
